server:
  port: 8282

#spring:
#  security:
#    user:
#      name: akeed
#      password: akeed123
#      roles: ADMIN,USER
#
#security:
#  oauth2:
#    client:
#      client-id: mobile
#      client-secret: pin
#      access-token-validity-seconds: 3600
#      authorized-grant-types: refresh_token, authorization-code,password,client-credentials
#      scope: READ,WRITE
#    authorization:
#      check-token-access: permitAll
