spring:
  application:
    name: task
  datasource:
    url: jdbc:mysql://localhost:3306/taskDB?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: akeed
    driver-class-name: com.mysql.jdbc.Driver
