server:
  port: 8090

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/akeed669/microservices-course-on-youtube-config-store
          search-paths:
            - 'service-config/*service'
  application:
    name: membership