server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  datacenter: Colombo-SriLanka
  environment: production
#  wait-time-in-ms-when-sync-empty: 0

  server:
      enableSelfPreservation: false